include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/clash_generated_bindings.dart

linter:
  rules:
    use_build_context_synchronously: true
    cancel_subscriptions: true
    sized_box_for_whitespace: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_print: true
    no_duplicate_case_values: true
