targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          - lib/main.dart

      # This part is needed to tell original reflectable builder to stay away
      # it overrides default options for reflectable builder to an **empty** set of files
      reflectable:
        generate_for:
          - no/files

      slang_build_runner:
        options:
          base_locale: zh
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: strings.g.dart
          lazy: false
          locale_handling: true
          flutter_integration: true
          translate_var: t
          enum_name: AppLocale
          key_case: camel
          string_interpolation: dart
