display_name: Singcast
icon: assets/icon.png
generic_name: Proxy Application
categories:
  - Network
  - Science
  - Development
  - System
keywords:
  - Proxy
  - VPN
  - sing-box
  - Application
startup_notify: true
include: []
