name: Runner
options:
  bundleIdPrefix: cn.mapleafgo
  deploymentTarget:
    iOS: "13.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SDKROOT: iphoneos
    ENABLE_BITCODE: NO
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    COPY_PHASE_STRIP: NO
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES

configs:
  Debug: debug
  Release: release
  Profile: release

targets:
  Runner:
    type: application
    platform: iOS
    sources:
      - path: Runner
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.mapleafgo.singcast
        PRODUCT_NAME: "$(TARGET_NAME)"
        INFOPLIST_FILE: Runner/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: "Runner/Runner-Bridging-Header.h"
        CURRENT_PROJECT_VERSION: "$(FLUTTER_BUILD_NUMBER)"
        VERSIONING_SYSTEM: "apple-generic"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        CODE_SIGN_ENTITLEMENTS: Runner/Runner.entitlements
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          ONLY_ACTIVE_ARCH: YES
    configFiles:
      Debug: Flutter/Debug.xcconfig
      Release: Flutter/Release.xcconfig
      Profile: Flutter/Release.xcconfig
    dependencies:
      - target: ExtensionProvider
      - framework: Frameworks/libsingcast-darwin.xcframework
        embed: true
      - sdk: NetworkExtension.framework
        weak: true
    preBuildScripts:
      - name: "Run Script"
        script: |
          /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
        inputFiles:
          - "$(SRCROOT)/Flutter/Generated.xcconfig"
    postBuildScripts:
      - name: "Thin Binary"
        script: |
          /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
        inputFiles:
          - "$(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)"

  ExtensionProvider:
    type: application.extension
    platform: iOS
    sources:
      - path: ExtensionProvider
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.mapleafgo.singcast.tunnel
        PRODUCT_NAME: "$(TARGET_NAME)"
        INFOPLIST_FILE: ExtensionProvider/Info.plist
        CURRENT_PROJECT_VERSION: "$(FLUTTER_BUILD_NUMBER)"
        VERSIONING_SYSTEM: "apple-generic"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
        CODE_SIGN_ENTITLEMENTS: ExtensionProvider/ExtensionProvider.entitlements
        SWIFT_EMIT_LOC_STRINGS: YES
        APPLICATION_EXTENSION_API_ONLY: NO
    dependencies:
      - framework: Frameworks/libsingcast-darwin.xcframework
        embed: true
      - sdk: NetworkExtension.framework

  RunnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RunnerTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.mapleafgo.singcast.RunnerTests
        PRODUCT_NAME: "$(TARGET_NAME)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Runner.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Runner"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - target: Runner
