
// Objective-C API for talking to the following Go packages
//
//	github.com/mapleafgo/singcast/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Singcast_FRAMEWORK_H__
#define __Singcast_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
