// Objective-C API for talking to github.com/mapleafgo/singcast/mobile Go package.
//   gobind -lang=objc github.com/mapleafgo/singcast/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileSingcast;
@protocol MobileEventListener;
@class MobileEventListener;
@protocol MobileInterfaceProvider;
@class MobileInterfaceProvider;
@protocol MobileSocketProtector;
@class MobileSocketProtector;
@protocol MobileWiFiStateProvider;
@class MobileWiFiStateProvider;

@protocol MobileEventListener <NSObject>
- (void)onEvent:(int32_t)eventType json:(NSString* _Nullable)json;
@end

@protocol MobileInterfaceProvider <NSObject>
- (NSString* _Nonnull)getInterfaces;
@end

@protocol MobileSocketProtector <NSObject>
- (BOOL)protect:(int32_t)fd;
@end

@protocol MobileWiFiStateProvider <NSObject>
- (NSString* _Nonnull)getWiFiState;
@end

/**
 * Singcast is the primary API object for mobile consumers.

Lifecycle:

	Create() → Init(homeDir) → [SetTunFd/SetSocketProtector/…] → StartWithContent → running
	   ↑                                                                     │
	   └── Stop ←────────────────────────────────────────────────────────────┘
	Destroy is terminal; call it when the OS reclaims the VPN service.
 */
@interface MobileSingcast : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * CheckConfig validates a config string (Clash YAML or sing-box JSON).
 */
- (BOOL)checkConfig:(NSString* _Nullable)content error:(NSError* _Nullable* _Nullable)error;
/**
 * CloseAllConnections closes all active connections.
 */
- (BOOL)closeAllConnections:(NSError* _Nullable* _Nullable)error;
/**
 * CloseConnection closes a connection by ID.
 */
- (BOOL)closeConnection:(NSString* _Nullable)id_ error:(NSError* _Nullable* _Nullable)error;
/**
 * Destroy releases all resources. The instance cannot be reused.
 */
- (void)destroy;
/**
 * FlushDNSCache clears the internal DNS query cache.
 */
- (BOOL)flushDNSCache:(NSError* _Nullable* _Nullable)error;
/**
 * FlushFakeIP clears the FakeIP address cache.
 */
- (BOOL)flushFakeIP:(NSError* _Nullable* _Nullable)error;
/**
 * FlushSystemDNS attempts to flush the system DNS cache.
 */
- (void)flushSystemDNS;
/**
 * Init initializes the core runtime.
optionsJSON: {"home_dir":"/path","debug":false}
 */
- (BOOL)init_:(NSString* _Nullable)optionsJSON error:(NSError* _Nullable* _Nullable)error;
/**
 * QueryConnections returns active connections as JSON.
 */
- (NSString* _Nonnull)queryConnections;
/**
 * QueryMode returns current routing mode and available modes as JSON.
 */
- (NSString* _Nonnull)queryMode;
/**
 * QueryProxies returns proxy groups as JSON.
 */
- (NSString* _Nonnull)queryProxies;
/**
 * QueryRules returns the routing rule list as JSON.
 */
- (NSString* _Nonnull)queryRules;
/**
 * QueryStats returns traffic and memory stats as JSON.
 */
- (NSString* _Nonnull)queryStats;
/**
 * ResetNetwork resets all connections, DNS cache, and forces outbounds to reconnect.
 */
- (void)resetNetwork;
/**
 * SelectProxy selects a proxy in the given group.
 */
- (BOOL)selectProxy:(NSString* _Nullable)group tag:(NSString* _Nullable)tag error:(NSError* _Nullable* _Nullable)error;
/**
 * SetGroupExpand sets the UI expand state for a proxy group.
 */
- (BOOL)setGroupExpand:(NSString* _Nullable)group expand:(BOOL)expand error:(NSError* _Nullable* _Nullable)error;
/**
 * SetIncludeAllNetworks sets whether the VPN uses includeAllNetworks (iOS).
 */
- (void)setIncludeAllNetworks:(BOOL)v;
- (void)setInterfaceProvider:(id<MobileInterfaceProvider> _Nullable)p0;
/**
 * SetLogLevel sets the minimum log level (2=Error, 3=Warn, 4=Info, 5=Debug, 6=Trace).
 */
- (void)setLogLevel:(int32_t)level;
/**
 * SetMemoryLimit sets a soft memory limit for Go runtime OOM protection.
Set to 0 to disable.
 */
- (void)setMemoryLimit:(int64_t)bytes;
/**
 * SetMode sets the clash routing mode (rule, global, or direct).
 */
- (BOOL)setMode:(NSString* _Nullable)mode error:(NSError* _Nullable* _Nullable)error;
- (void)setOnEvent:(id<MobileEventListener> _Nullable)l;
/**
 * SetSocketProtector registers a socket protector for VPN bypass.
Pass nil to clear the protector (e.g. when VPN disconnects).
 */
- (void)setSocketProtector:(id<MobileSocketProtector> _Nullable)p0;
/**
 * SetTunFd stores a TUN file descriptor for mobile platforms.
 */
- (void)setTunFd:(int32_t)fd;
- (void)setWiFiStateProvider:(id<MobileWiFiStateProvider> _Nullable)p0;
/**
 * StartWithContent starts or restarts the service with raw YAML or JSON config.
 */
- (BOOL)startWithContent:(NSString* _Nullable)content ruleSetProxy:(NSString* _Nullable)ruleSetProxy error:(NSError* _Nullable* _Nullable)error;
/**
 * State returns the current service lifecycle state as a string.
"created", "initialized", "starting", "running", "destroyed".
 */
- (NSString* _Nonnull)state;
/**
 * Stop stops the running service. Safe to call multiple times.
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
/**
 * TestDelay runs a URL test for the given outbound tag.
Returns delay in milliseconds, -1 on error or timeout.
 */
- (int32_t)testDelay:(NSString* _Nullable)name timeoutMs:(int32_t)timeoutMs;
/**
 * TestGroupDelay runs URL tests for all outbounds in a group.
Returns a JSON map of {tag: delay_ms}. -1 means failure/timeout.
 */
- (NSString* _Nonnull)testGroupDelay:(NSString* _Nullable)groupTag timeoutMs:(int32_t)timeoutMs;
/**
 * TriggerGC forces a garbage collection.
 */
- (void)triggerGC;
/**
 * UpdateDefaultInterface reports the current default network interface.
 */
- (void)updateDefaultInterface:(NSString* _Nullable)name index:(int64_t)index expensive:(BOOL)expensive;
/**
 * Version returns version info as JSON.
 */
- (NSString* _Nonnull)version;
@end

/**
 * Create creates a new Singcast instance.
 */
FOUNDATION_EXPORT MobileSingcast* _Nullable MobileCreate(void);

@class MobileEventListener;

@class MobileInterfaceProvider;

@class MobileSocketProtector;

@class MobileWiFiStateProvider;

/**
 * EventListener is the unified callback interface for all core events.
eventType: 0=Log, 1=URLTest, 2=ModeUpdate, 3=ConnEvent, 4=StateChange, 5=Stats.
 */
@interface MobileEventListener : NSObject <goSeqRefInterface, MobileEventListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onEvent:(int32_t)eventType json:(NSString* _Nullable)json;
@end

/**
 * InterfaceProvider provides network interface data on demand.
GetInterfaces must return a JSON array of interface objects.
 */
@interface MobileInterfaceProvider : NSObject <goSeqRefInterface, MobileInterfaceProvider> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)getInterfaces;
@end

/**
 * SocketProtector protects socket file descriptors from VPN routing.
On Android, implement this to call VpnService.protect(fd).
 */
@interface MobileSocketProtector : NSObject <goSeqRefInterface, MobileSocketProtector> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)protect:(int32_t)fd;
@end

/**
 * WiFiStateProvider provides WiFi state on demand.
GetWiFiState must return {"ssid":"...","bssid":"..."}.
 */
@interface MobileWiFiStateProvider : NSObject <goSeqRefInterface, MobileWiFiStateProvider> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)getWiFiState;
@end

#endif
